### ISSUE TITLE
Error during instalation, README not found

### ISSUE THREAD

**Issue by rafaelcapucho** [nlsdfnbch/btfxwss#18]
Hi, I'm getting this, thanks.

```
$ sudo pip3 install btfxwss
[sudo] password for user: 
Collecting btfxwss
  Downloading btfxwss-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-byx62y6k/btfxwss/setup.py", line 8, in <module>
        long_description=open('README.rst').read())
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-byx62y6k/btfxwss/
```

The last version, download here directly seems to install, could you update the package on pypi if possible?

```
$ sudo pip3 install /tmp/btfxwss-master.zip 
[sudo] password for user: 
Processing /tmp/btfxwss-master.zip
Requirement already satisfied: websocket-client in /usr/lib/python3.6/site-packages (from btfxwss==1.0.1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from websocket-client->btfxwss==1.0.1)
Installing collected packages: btfxwss
  Running setup.py install for btfxwss ... done
Successfully installed btfxwss-1.0.1
```

**Comment by nlsdfnbch** [comment]
Hey Rafael! 

Absolutely!  I'll fix this today.  Thank you for reporting! 

Cheers, 

Nils

**Comment by nlsdfnbch** [comment]
I *may* have fixed this issue - the problem was that setup.py in the distributed package wanted to open the readme, which isn't packaged along with it. I've fixed this with a dirty workaround.  Mainly because I just got out of bed and didn't stop to think about how this issue would be resolved with a simple entry in a setup.cfg file (I blame the lack of coffee).

Anyway, it works for me now (but so it did before) - so if you can, check if the pip install works now for you?

**Comment by rafaelcapucho** [comment]
Working perfectly, thx.

```
sudo pip3 install btfxwss --force-reinstall --upgrade
Collecting btfxwss
  Downloading btfxwss-1.0.3.zip
Collecting websocket-client (from btfxwss)
  Downloading websocket_client-0.44.0-py2.py3-none-any.whl (199kB)
    100% |████████████████████████████████| 204kB 1.0MB/s 
Collecting six (from websocket-client->btfxwss)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, websocket-client, btfxwss
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: websocket-client 0.44.0
    Uninstalling websocket-client-0.44.0:
      Successfully uninstalled websocket-client-0.44.0
  Found existing installation: btfxwss 1.0.3
    Uninstalling btfxwss-1.0.3:
      Successfully uninstalled btfxwss-1.0.3
  Running setup.py install for btfxwss ... done
Successfully installed btfxwss-1.0.3 six-1.10.0 websocket-client-0.44.0
```
