### ISSUE TITLE
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

### ISSUE THREAD

**Issue by ntom** [nlsdfnbch/btfxwss#25]
I setup the script collecting some candles, 

After chewing through around 6700 candles worth of data... I got this error..

`2017-08-21 12:18:16,802 -- INFO -- connection 179 -- Connection Error - Connection is already closed.`

I got quite a few of these..

```
2017-08-21 13:31:32,821 -- INFO -- connection 121 -- Attempting to connect again in 10 seconds.
2017-08-21 13:31:43,501 -- INFO -- connection 179 -- Connection Error - Handshake status 525
2017-08-21 13:31:43,508 -- INFO -- connection 168 -- Connection closed
```

a few of these ...

```
2017-08-21 13:33:37,691 -- INFO -- connection 173 -- Connection opened
2017-08-21 13:33:47,819 -- INFO -- connection 121 -- Attempting to connect again in 10 seconds.
2017-08-21 13:33:58,525 -- INFO -- connection 179 -- Connection Error - Handshake status 520
2017-08-21 13:33:58,533 -- INFO -- connection 168 -- Connection closed
```

And a few of these...
```
2017-08-21 14:19:28,177 -- INFO -- connection 168 -- Connection closed
2017-08-21 14:19:28,183 -- INFO -- connection 121 -- Attempting to connect again in 10 seconds.
2017-08-21 14:19:38,764 -- INFO -- connection 179 -- Connection Error - Handshake status 302
```

Ultimately the script after 2 hours of trying produced .. 

```
2017-08-21 15:25:25,719 -- INFO -- connection 173 -- Connection opened
Exception in thread Thread-21958:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/apache2/htdocs/Bots/btfxwss/connection.py", line 218, in send_ping
    self.conn.send(json.dumps({'event': 'ping'}))
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by nlsdfnbch** [comment]
Hey @ntom!
Code 5xx are server-side issues, which usually indicate that the API is currently not working properly. Code 302 depends a bit on Bitfinex - this may either be a Redirect, in which case I believe the `websocket` library wouldve taken care of that. That means that perhaps Bitfiex uses a 302 in place of a  303, which means that the URI we request (for logging in to the websocket) moved. 
I'll check if Bitfinex changed any addresses, but it's quite likely that this was just a temporary server issue.

**Comment by nlsdfnbch** [comment]
Does this issue persist for you?

**Comment by nlsdfnbch** [comment]
possibly related to #33

**Comment by ntom** [comment]
Hi @nlsdfnbch thanks for the reply sorry I minssed it . .  Yes i can see now how this is server side thanks for the update.
