### ISSUE TITLE
Candles fetch error

### ISSUE THREAD

**Issue by Closius** [nlsdfnbch/btfxwss#40]
I'm trying to fetch candles with timeframe more than 1m.
`wss.candles(pair="BTCUSD", timeframe="15m")`

With '1m' its ok, but if I try to use other timeframes like "15m" I have an Error:

`Traceback (most recent call last):
  File "main.py", line 192, in <module>
    candles[kind]['queue'] = wss.candles(pair=PAIR, timeframe=kind)
  File "/Users/anton/anaconda/lib/python3.5/site-packages/btfxwss/client.py", line 278, in candles
    raise KeyError(pair)
KeyError: 'BTCUSD'
`

I also try to fetch this data from Websocket Playground https://bitfinex.readme.io/v2/reference#ws-public-candle there is no problem.

**Comment by Closius** [comment]
My mistake. I have to subscribe to channel first with timeframe
`wss.subscribe_to_candles(PAIR, timeframe=kind)`
