### ISSUE TITLE
Errors in `BtfxWss()._handle_book` and `Orders().__call__`  

### ISSUE THREAD

**Issue by Leobouloc** [nlsdfnbch/btfxwss#5]
I put both errors in the same issue as I am unsure how both are linked and how one fix affects the other...

When running the sample code in the documentation, I get the following error:

```
Exception in thread Processing Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/XXX/.local/lib/python3.5/site-packages/btfxwss/classes.py", line 399, in process
    self.handle_data(ts, data)
  File "/home/XXX/.local/lib/python3.5/site-packages/btfxwss/classes.py", line 605, in handle_data
    self.channels[chan_id](ts, chan_id, data)
  File "/home/XXX/.local/lib/python3.5/site-packages/btfxwss/classes.py", line 645, in _handle_book
    price, count, amount = order
ValueError: too many values to unpack (expected 3)
```

This fix in `_handle_data` seems to avoid having an error but I don't know if this is the behavior you intended:

```
    def _handle_book(self, ts, chan_id, data):
        """
        Updates the order book stored in self.books[chan_id]
        :param ts: timestamp, declares when data was received by the client
        :param chan_id: int, channel id
        :param data: dict, tuple or list of data received via wss
        :return:
        """
        label = self.channel_labels[chan_id][1]['pair']
        assert len(data) == 1
        data = data[0]
        if isinstance(data[0], list):
            # snapshot
            
            for order in data:
                price, count, amount = order
                side = (self.books[label].bids if amount > 0
                        else self.books[label].asks)
                side[str(price)] = (price, amount, count, ts)
        else:
            # update
            price, count, amount = data
            side = (self.books[label].bids if amount > 0
                    else self.books[label].asks)
            if count == 0:
                # remove from book
                try:
                    side.pop(str(price))
                except KeyError:
                    # didn't exist, move along
                    pass
            else:
                # update in book
                side[str(price)] = (price, amount, count, ts)
```

Using this fix, I then get the following error, in  `wss.books['BTCUSD'].bids()`:

```
>>> time.sleep(5); wss.books['BTCUSD'].bids()
Traceback (most recent call last):

  File "<ipython-input-107-35d8e9dec676>", line 1, in <module>
    wss.books['BTCUSD'].bids()

  File "/home/leo/.local/lib/python3.5/site-packages/btfxwss/classes.py", line 45, in __call__
    reverse=self._reverse)]

  File "/home/leo/.local/lib/python3.5/site-packages/btfxwss/classes.py", line 44, in <listcomp>
    return [self._orders[i]() for i in sorted(self._orders.keys(),

TypeError: 'tuple' object is not callable
```

In this case, changing `self._orders[i]()` to `self._orders[i]` seems to remove the error.

**Comment by nlsdfnbch** [comment]
Cheers for the issue submission! The two aren't related, but dont worry about it ;D 
The first issue (the unpack error), used to happen for heartbeats and other data sent through the channels. I thought I had them all covered, but I left it in just in case something snuck by - congrats, you've found an unhandled case!
Is there any chance you've logged it? `handle_data` should write a log message in this case. That way I can adjust the handler appropriately.

The latter is simply a copy & paste Error. Your fix is exactly what needs fixing, since `self._orders` is just a dict of tuples.

**Comment by Leobouloc** [comment]
Thanks! I have a log, but it's a bit too large to upload or paste. I'll try isolating the problem and send you a shorter log this weekend.

**Comment by nlsdfnbch** [comment]
I actually double-checked just now - I raise a `FaultyPayloadError` without actually catching that exception (so no log entry, shame on me) - I'll fix that, but perhaps the trasceback was written to your log nevertheless. searching / grepping for `FaultyPayloadError` should yield the line.
