### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by vinaykashyap1206** [nlsdfnbch/btfxwss#58]
Traceback (most recent call last):
  File "contrib/live_data_feeders/bitfinex_data_feeder.py", line 1, in <module>
    from btfxwss import BtfxWss
  File "/home/arajguru/work/CCPlatform_Private/venvpython3/lib/python3.4/site-packages/btfxwss/__init__.py", line 1, in <module>
    from btfxwss.client import BtfxWss
  File "/home/arajguru/work/CCPlatform_Private/venvpython3/lib/python3.4/site-packages/btfxwss/client.py", line 9, in <module>
    from btfxwss.connection import WebSocketConnection
  File "/home/arajguru/work/CCPlatform_Private/venvpython3/lib/python3.4/site-packages/btfxwss/connection.py", line 266
    self.q.put((event, data, *args))
                                   ^
SyntaxError: can use starred expression only as assignment target

**Comment by nlsdfnbch** [comment]
Starred expressions in this manner are only available in Python 3.5+, which is the version the library is tested against. Feel free to supply a fix for pre-3.5 versions via a PR!
Either way, thanks for your contribution!
