### ISSUE TITLE
Raise an KeyError exception when _info_handler recives a version message.

### ISSUE THREAD

**Issue by csrocha** [nlsdfnbch/btfxwss#98]
Hi, I test the code that you share in the README. I execute it and it returns this error:

```
Traceback (most recent call last):
  File "/home/crocha/Projects/btfxwss/btfxwss/connection.py", line 400, in _info_handler
    self.log.info(info_message[data['code']])
KeyError: 'code'
ERROR:websocket:error from callback <bound method WebSocketConnection._on_message of <WebSocketConnection(Thread-1, started daemon 140105430472448)>>: 'code'
  File "/home/crocha/.local/lib/python3.6/site-packages/websocket/_app.py", line 269, in _callback
    callback(self, *args)
  File "/home/crocha/Projects/btfxwss/btfxwss/connection.py", line 169, in _on_message
    self._system_handler(data, received_at)
  File "/home/crocha/Projects/btfxwss/btfxwss/connection.py", line 359, in _system_handler
    self._info_handler(data)
  File "/home/crocha/Projects/btfxwss/btfxwss/connection.py", line 405, in _info_handler
    self.log.error("Unknown Info code %s!", data['code'])

```

The data variable have the value:

`{'version': 2}`

**Comment by nlsdfnbch** [comment]
Merged and uploaded to pypi! Thanks for the contribution!
